// @ts-nocheck — subsistema "NEXATIXS CORE Phase 2" sin terminar: referencia
// tablas (profiles, nxt_master_clients, etc.) que no existen en este proyecto
// de Supabase. No enlazado desde ninguna pagina. Suprimido del type-check
// para no bloquear el build de esta sesion; pendiente terminarlo o borrarlo.
import { createClient } from '@/lib/supabase/server';
import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();

    // Verify user is superadmin
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    // Check if user is superadmin
    const { data: profile, error: profileError } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single();

    if (profileError || profile?.role !== 'superadmin') {
      return NextResponse.json(
        { error: 'Only superadmin can create clients' },
        { status: 403 }
      );
    }

    const body = await request.json();
    const { razon_social, nombre_comercial, email_contacto, telefono, tipo_empresa } = body;

    // Validate input
    if (!razon_social) {
      return NextResponse.json(
        { error: 'razon_social is required' },
        { status: 400 }
      );
    }

    // Create master client (NXT-ID will be auto-generated by trigger)
    const { data: client, error: clientError } = await supabase
      .from('nxt_master_clients')
      .insert([
        {
          razon_social,
          nombre_comercial,
          email_contacto,
          telefono,
          tipo_empresa,
          estado: 'activo',
          created_by: user.id,
        },
      ])
      .select()
      .single();

    if (clientError) {
      console.error('Error creating client:', clientError);
      return NextResponse.json(
        { error: 'Failed to create client', details: clientError.message },
        { status: 500 }
      );
    }

    // Log action
    await supabase
      .from('nxt_audit_logs')
      .insert([
        {
          nxt_client_id: client.id,
          usuario_id: user.id,
          accion: 'create_client',
          entidad: 'nxt_master_clients',
          entidad_id: client.id,
          resultado: 'success',
          detalles: {
            razon_social: client.razon_social,
            nxt_id: client.nxt_id,
          },
        },
      ]);

    return NextResponse.json(
      {
        success: true,
        client: {
          id: client.id,
          nxt_id: client.nxt_id,
          razon_social: client.razon_social,
          email_contacto: client.email_contacto,
          estado: client.estado,
          created_at: client.created_at,
        },
      },
      { status: 201 }
    );
  } catch (error) {
    console.error('Unexpected error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const supabase = createClient();

    // Verify user is superadmin
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    // Get all clients (superadmin only)
    const { data: clients, error: clientsError } = await supabase
      .from('nxt_master_clients')
      .select(
        `
        id,
        nxt_id,
        razon_social,
        nombre_comercial,
        email_contacto,
        telefono,
        estado,
        created_at,
        nxt_licenses (
          id,
          plan,
          estado,
          product_id
        )
      `
      )
      .order('created_at', { ascending: false });

    if (clientsError) {
      return NextResponse.json(
        { error: 'Failed to fetch clients', details: clientsError.message },
        { status: 500 }
      );
    }

    return NextResponse.json(
      {
        success: true,
        total: clients?.length || 0,
        clients: clients || [],
      },
      { status: 200 }
    );
  } catch (error) {
    console.error('Unexpected error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
