-- Fase 5: seed del catalogo maestro de los 6 pilares de servicios.

insert into public.services_catalog (pillar_slug, item_name) values
  ('desarrollo', 'Software a medida'),
  ('desarrollo', 'Aplicaciones Web'),
  ('desarrollo', 'Aplicaciones móviles'),
  ('desarrollo', 'APIs'),
  ('desarrollo', 'Sistemas ERP'),
  ('desarrollo', 'CRM'),
  ('infraestructura', 'Servidores'),
  ('infraestructura', 'Redes'),
  ('infraestructura', 'Virtualización'),
  ('infraestructura', 'Active Directory'),
  ('infraestructura', 'NAS'),
  ('infraestructura', 'Home Lab'),
  ('infraestructura', 'Monitoreo'),
  ('automatizacion', 'Power Automate'),
  ('automatizacion', 'IA'),
  ('automatizacion', 'Bots'),
  ('automatizacion', 'Integraciones'),
  ('automatizacion', 'IoT'),
  ('cloud', 'Microsoft Azure'),
  ('cloud', 'AWS'),
  ('cloud', 'Google Cloud'),
  ('cloud', 'Microsoft 365'),
  ('cloud', 'Google Workspace'),
  ('ciberseguridad', 'Firewalls'),
  ('ciberseguridad', 'Antivirus empresarial'),
  ('ciberseguridad', 'Auditorías'),
  ('ciberseguridad', 'Pentesting'),
  ('ciberseguridad', 'Backups'),
  ('ciberseguridad', 'Recuperación ante desastres'),
  ('soporte', 'Mesa de ayuda'),
  ('soporte', 'Mantenimiento preventivo'),
  ('soporte', 'Soporte remoto'),
  ('soporte', 'Soporte presencial')
on conflict do nothing;
